### ISSUE TITLE
peak normalizetion vs SMInput

### ISSUE THREAD

**Issue by zhangjun-123** [YeoLab/eclip#10] opened 2020-09-01 08:08 UTC
Hi,i am analysing the eclip data following your protocol,but i got a problem at the last step in peak normaliztion.This my error in the  linux terminal.

$perl perl_scripts/overlap_peakfi_with_bam_PE.pl second-read-bam/RBFOX2-rep1.adapterTrim.round2.rmRep.rmDup.sorted.combined.r2.sorted.bam second-read-bam/RBFOX2-Input-rep1.adapterTrim.round2.rmRep.rmDup.sorted.combined.r2.sorted.bam input-norm/RBFOX2-rep1.combined.r2.peaks.bed input-norm/ip1_mapped_readnum.txt input-norm/input1_mapped_readnum.txt input-norm/RBFOX2-rep1.normed.bed
**reading peak file input-norm/RBFOX2-rep1.combined.r2.peaks.bed
now doing expt second-read-bam/RBFOX2-rep1.adapterTrim.round2.rmRep.rmDup.sorted.combined.r2.sorted.bam
now doing input second-read-bam/RBFOX2-Input-rep1.adapterTrim.round2.rmRep.rmDup.sorted.combined.r2.sorted.bam
Use of uninitialized value in division (/) at perl_scripts/overlap_peakfi_with_bam_PE.pl line 67.
Illegal division by zero at perl_scripts/overlap_peakfi_with_bam_PE.pl line 67.**
     
      I donot know how to fix it.Can you help me?

**Comment by byee4** [comment] 2020-09-01 18:15
What is the contents of your 

```
input-norm/ip1_mapped_readnum.txt 
input-norm/input1_mapped_readnum.txt
```

?

Can you share?

**Comment by zhangjun-123** [comment] 2020-09-02 01:16
![image](https://user-images.githubusercontent.com/64965509/91920992-fc7a2b00-ecfc-11ea-98cc-55ac5c2bffad.png)
![image](https://user-images.githubusercontent.com/64965509/91921012-0ac84700-ecfd-11ea-8353-39a0dcafd1dc.png)

**Comment by zhangjun-123** [comment] 2020-09-02 12:50
Hi,this is the input1 and ip1 contents,besides there is the bed file contents.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YeoLab/eclip"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月2日(星期三) 凌晨2:16
收件人:&nbsp;"YeoLab/eclip"<eclip@noreply.github.com&gt;;
抄送:&nbsp;"内含子寻外显子"<1138976957@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YeoLab/eclip] peak normalizetion vs SMInput (#10)





 
What is the contents of your
 input-norm/ip1_mapped_readnum.txt  input-norm/input1_mapped_readnum.txt  
?
 
Can you share?

**Comment by byee4** [comment] 2020-09-08 00:20
Is this a Windows machine that you're working from (the notebook app looks like windows)? I wonder if there is an issue with newline characters being added that aren't expected to be there. If you can, can you create the file in linux with those numbers (do not copy/paste) and retry? Else if you can attach the text files themselves we can try reproducing the error.

**Comment by zhangjun-123** [comment] 2020-09-08 01:39
Hi,dear yeo,i am using WSL(windows subsysterm linux ) to perform the peak normalizatin,should i do it on ubuntu systerm ? or maybe this problem will be solved? thank you for your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YeoLab/eclip"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 上午8:20
收件人:&nbsp;"YeoLab/eclip"<eclip@noreply.github.com&gt;;
抄送:&nbsp;"内含子寻外显子"<1138976957@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YeoLab/eclip] peak normalizetion vs SMInput (#10)





 
Is this a Windows machine that you're working from (the notebook app looks like windows)? I wonder if there is an issue with newline characters being added that aren't expected to be there. If you can, can you create the file in linux with those numbers (do not copy/paste) and retry? Else if you can attach the text files themselves we can try reproducing the error.

**Comment by byee4** [comment] 2020-09-08 16:51
I don't know about WSL specifically but it shouldn't matter which linux flavor you use. Can you try using these files (attached) to see if that fixes the issue?
[input1_mapped_readnum.txt](https://github.com/YeoLab/eclip/files/5189696/input1_mapped_readnum.txt)
[ip1_mapped_readnum.txt](https://github.com/YeoLab/eclip/files/5189698/ip1_mapped_readnum.txt)

**Comment by zhangjun-123** [comment] 2020-09-09 14:37
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Hi, dear yeo ,i have used the 'mapped_num.txt' file you offered,but problem is still the same. Luckily,i figure this out on ubuntu systerm ,thank you for your patiene and time ! Besides, i have another question, i use the clipper version 0.20 to callpeak ,the peaks numbers is about 20,000, but i got peak numbers about 550,000 in the same bam file when i use the latest clipper version 2.00 , is the&nbsp;phenomenon normal ? this is my code :&nbsp;


clipper -s hg19 -b second-read-bam/RBFOX2-rep1.adapterTrim.round2.rmRep.rmDup.sorted.combined.r2.sorted.bam -o bed-file/RBFOX2-rep1.2.0.test.bed --save-pickle.&nbsp;
Thank you for your reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YeoLab/eclip"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 凌晨0:51
收件人:&nbsp;"YeoLab/eclip"<eclip@noreply.github.com&gt;;
抄送:&nbsp;"内含子寻外显子"<1138976957@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YeoLab/eclip] peak normalizetion vs SMInput (#10)





 
I don't know about WSL specifically but it shouldn't matter which linux flavor you use. Can you try using these files (attached) to see if that fixes the issue?
 input1_mapped_readnum.txt
 ip1_mapped_readnum.txt

**Comment by byee4** [comment] 2020-09-09 17:41
There should not be that big of a difference between Clipper versions. You may get more help in the official CLIPper repository, might be invisible characters or an encoding issue if you're working in two different environments? 

To get the actual peak number, you will need to normalize them above input and filter for p-value and fold change cutoffs. If this is RBFOX2 from ENCODE, you can compare your result to the narrowPeak files (for example, [here](https://www.encodeproject.org/files/ENCFF639MYI/@@download/ENCFF639MYI.bed.gz)) to make sure you're getting the correct results.

**Comment by byee4** [comment] 2020-09-29 00:37
Closing, re-open if this is still a problem.

**Closed by byee4** 2020-09-29 00:37 UTC
